# Определяем версию yaml файла
version: '3.8'

# Определяем различные сервисы(в данном случае только web) 
services:
  #Определяем веб-сервис
  web:
    #Указываем рассположение сервиса относительно compose.yaml
    build: ./website
    #Порт мэппинг
    ports:
      - 3000:3000
    #Защищаем от сбоев в системе(контейнер будет автоматически перезапускаться) 
    restart: always